---
- name: check for short-circuit
  raw: "> /dev/null command -v tig;"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: "{{installed|failed or not tig_should_shortcircuit}}"

- include: compat.yml

- include: include_vars.yml

# Install EPEL
- include: epel.yml
  when: ansible_distribution == 'CentOS'

- include: install_package_names.yml
